# Generated by Django 4.2.13 on 2024-05-28 18:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("S", "Science&Tech"),
                            ("F", "Fiction"),
                            ("B", "Biography"),
                            ("T", "Travel"),
                            ("O", "Other"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("num_pages", models.PositiveIntegerField(default=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Regular Member"),
                            (2, "Premium Member"),
                            (3, "Guest Member"),
                        ],
                        default=1,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("city", models.CharField(default="Windsor", max_length=20)),
                ("province", models.CharField(default="ON", max_length=2)),
                ("last_renewal", models.DateField(default=django.utils.timezone.now)),
                ("auto_renew", models.BooleanField(default=True)),
                ("borrowed_books", models.ManyToManyField(blank=True, to="myapp.book")),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("website", models.URLField()),
                ("city", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="USA", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.IntegerField(
                        choices=[(0, "Purchase"), (1, "Borrow")], default=1
                    ),
                ),
                ("order_date", models.DateField(default=django.utils.timezone.now)),
                ("books", models.ManyToManyField(to="myapp.book")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.member"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="myapp.publisher",
            ),
        ),
    ]
