# Generated by Django 4.2.13 on 2024-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="favorite_books",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_order_books", to="myapp.book"
            ),
        ),
    ]
