# Generated by Django 4.2.13 on 2024-06-04 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_order_favorite_books"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="favorite_books",
        ),
    ]
