# Generated by Django 4.2.13 on 2024-07-09 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_book_num_reviews_review"),
        ("myapp", "0003_remove_order_favorite_books"),
    ]

    operations = []
