# Generated by Django 5.0.6 on 2024-06-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_of', to='myapp.book'),
        ),
    ]
