# Generated by Django 4.2.13 on 2024-07-09 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_merge_20240709_1710"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="num_reviews",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
