# Generated by Django 5.0.6 on 2024-07-03 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_member_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='book',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='borrowed_by', to='myapp.book'),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(default='Windsor', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(1, 'Regular Member'), (2, 'Premium Member'), (3, 'Guest Member')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='USA', max_length=20),
        ),
    ]
